
<?php if ($success) : ?>

	<script>$('#remote-modal').find('.close').trigger('click');</script>

<?php else : ?>
	N'hésitez pas à nous contacter pour toute demande, question ou report de bug.<br><br>  

	<?= $form->open_tag() ?>
	<?= $form->get('subject')->style('width:100%; margin-bottom:10px;')->draw() ?>
	<?= $form->get('message')->style('width:100%; margin-bottom:10px; min-height:300px;')->draw() ?>
	<?= $form->get('submit')->style('float:right; width:150px;')->draw() ?>
	<div class="clear"></div>
	</form>

<?php endif; ?>