
<?php if ($step != 1) : ?>
    <a href="/install?step=<?= $step - 1 ?>" class="pull-right"><?= $this->icon('arrow-left', 'lg') ?> Retour</a>
<?php endif; ?>

<?php if ($step == 1) : ?>

    <h1>Installation de Cobalt - Etape 1 : Séléction des modules</h1>

    <div style="width:700px;">
    <?= $form->draw(); ?>
    </div>

<?php elseif ($step == 2) : ?>

    <h1>Installation de Cobalt - Etape 2 : Configuration</h1>

    <div style="width:700px;">
    <?= $form->draw(); ?>
    </div>

<?php elseif ($step == 3) : ?>

    <h1>Installation de Cobalt - Etape 3 : Connexion base de donnée</h1>

    <div style="width:700px;">
    Créez une base de donnée vide et en indiquer le nom et les accès <br><br>

    <?= $form->draw(); ?>
    </div>

<?php elseif ($step == 4) : ?>

    <h1>Installation terminée</h1>

    <div style="width:700px;">
        <div class="red">
        <?= $this->full_install(); ?>
        <?php if ($have_towns) : ?>
        La table "towns" n'a pas pu être installée automatiquement car trop lourde, installez la manuellement via le fichier Core/Base/install/tables/_towns.sql avant de supprimer les fichiers d'installation.
        <?php endif; ?>
        </div>
        <br>
        <?php if ($have_front) : ?>
        <a href="/" target="_blank" class="btn btn-primary" style="color:white">Accéder au front-office</a><br><br>
        <?php endif; ?>
        <?php if ($have_admin) : ?>
        <a href="/admin/login" target="_blank" class="btn btn-primary" style="color:white">Accéder au panel admin (admin/admin)</a><br><br>
        <?php endif; ?>   
        <?php if ($have_superadmin) : ?>
        <a href="/superadmin/login" target="_blank" class="btn btn-primary" style="color:white">Accéder au panel superadmin</a><br><br>
        <?php endif; ?>
        <a href="/panel" target="_blank" class="btn btn-primary" style="color:white">Accéder au panel Développeur</a><br><br>

        <?php if ($_SERVER['SERVER_NAME'] != 'cobalt.dev') : ?>
        <a href="/install?step=5" target="_blank" data-confirm="Confirmer la suppression des fichiers d'installation?"  class="btn btn-warning" style="color:white">Supprimer les fichiers d'installtion</a><br><br>
        <?php endif; ?>
    </div>

<?php elseif ($step == 5) : ?>

    <h1>Suppression des fichiers d'installation</h1>

    Les fichiers ont bien été supprimés.

<?php endif; ?>