

    <?php if ($action == 'list') : ?>

        <section>

            <div class="row table-control">

                <div class="col-sm-6">
                    <h2>Liste des campagnes SMS</h2>
                </div>

                <div id="update_status" data-update-url="<?= $this->url('superadmin-json-get_status'); ?>"></div>

                <div class="col-sm-6" style="padding-top:10px;">
                    <a href="#" id="add-campain" data-ajax="<?= $this->url('superadmin-widget-campain_sms', array('action'=>'form')) ?>" data-transition="slide-left" class="button inverse"><?= $this->icon('mobile') ?>  Nouvelle campagne SMS</a>
                </div>

            </div>

            <div class="table-responsive">
                <?= $table->draw() ?>
            </div>

        </section>
    
    <?php elseif ($action == 'form') : ?>

        <section>

            <a href="#" class="return-arrow" data-ajax="<?= $this->url('superadmin-widget-campain_sms', array('action' => 'list')) ?>" data-transition="slide-right" style="position:absolute; top:-130px; right:15px;">
                <?= $this->icon('arrow-left') ?><!--arrow-circle-o-left-->
            </a>

            <h2><?= !$form->get('id')->value ? 'Ajouter' : 'Modifier' ?> une campagne SMS</h2>

            <?= $form->draw('1000px'); ?>

            <style>
            <?= $editor_css; ?>
            </style>
    
        </section>

    <?php elseif ($action == 'view') : ?>

        <section data-campain-id="<?= $campain->id ?>" data-campain-type="<?= $type ?>">

            <div id="popup_status" class="<?= $status['color'] ?>">
                <?= $this->icon('envelope', 'x2'); ?><br>
                <span><?= $status['label'] ?></span>
            </div>
            
            <h2 style="margin-top:0;"><?= $campain->campain_title ?></h2>

            <hr class="clear">

            <div id="timeline">
                <span class="bg-line"></span>
                <span class="bullet-text" style="left:-40px;">Ciblage</span>
                <span class="bullet-text" style="right:215px;">Contenu</span>
                <span class="bullet-text" style="right:-40px;">Envoi</span>

                <span class="bullet<?= $status['target'] ? ' active' : '' ?> bullet2" style="left:0%;"></span>
                <span class="bullet<?= $status['content'] ? ' active' : '' ?> bullet3" style="right:48%;"></span>
                <span class="bullet<?= $status['sent'] == 2 || $status['sent'] == 3 ? ' active' : ($status['sent'] == 1 ? ' current' : '') ?> bullet4" style="right:0;"></span>
            </div>

            <div id="tabs-client">
                <ul class="nav nav-tabs">

                    <li<?= $active_tab == 'A' ? ' class="active"' : '' ?>><a data-toggle="tab" href="#sectionA">Ciblage</a></li>
                    <li<?= $active_tab == 'B' ? ' class="active"' : '' ?>><a data-toggle="tab" href="#sectionB">Contenu</a></li>
                    <li<?= $active_tab == 'C' ? ' class="active"' : '' ?>><a data-toggle="tab" href="#sectionC" onCLick="javascript:refresh_send_tab();">Envoi</a></li>
                </ul>
                <div class="tab-content">

                    <div id="sectionA" class="tab-pane fade <?= $active_tab == 'A' ? ' in active' : '' ?>">
                        
                        <!-- CIBLAGE -->
                        <div id="ajax_container_target_campain" data-ajax-container="<?= $this->url('superadmin-widget-target_campain', array('id'=> $campain->id, 'type'=>$type)) ?>">
                            <?= $this->widget('target_campain', array('id'=> $campain->id, 'type'=>$type)); ?>
                        </div>

                    </div>
                    <div id="sectionB" class="tab-pane fade <?= $active_tab == 'B' ? ' in active' : '' ?>">
                        
                        <!-- CONTENU -->
                        <div id="ajax_container_content" data-ajax-container="<?= $this->url('superadmin-widget-campain_content_sms', array('id'=> $campain->id)) ?>">
                            <?= $this->widget('campain_content_sms'); ?>
                        </div>

                    </div>

                    <div id="sectionC" class="tab-pane fade <?= $active_tab == 'C' ? ' in active' : '' ?>">
                        
                        <!-- ENVOI -->
                         <div id="ajax_container_send_campain" data-ajax-container="<?= $this->url('superadmin-widget-launch_campain', array('id'=> $campain->id, 'type'=> $type)) ?>">
                            <?= $this->widget('launch_campain',array('id'=> $campain->id, 'type'=> $type)); ?>
                        </div>

                    </div>
                    
                </div>
            </div>

        </section>

    <?php endif; ?>