<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        
        <title><?= $this->page->base_title ?><?= $this->page->title ?></title>

        <?= $this->favicon() ?>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <?php foreach ($this->page->metas as $key => $value) : ?>
            <meta name="<?= $key ?>" content="<?= $value ?>">
        <?php endforeach; ?>
        
        <?php foreach ($this->page->stylesheets as $stylesheet) : ?>
            <link rel="stylesheet" href="<?= $stylesheet ?>?maj=<?= MAJ ?>" type="text/css">
        <?php endforeach; ?>

        <?php foreach ($this->page->less as $less_sheet) : ?>
            <link rel="stylesheet/less" href="<?= $less_sheet ?>?maj=<?= MAJ ?>" type="text/css">
        <?php endforeach; ?>

        <?php foreach ($this->page->scripts as $script) : ?>
            <script src="<?= $script ?>?maj=<?= MAJ ?>"  type="text/javascript"></script>
        <?php endforeach; ?>

        <?php foreach ($this->page->google_font as $font) : ?>
            <link href='//fonts.googleapis.com/css?family=<?= $font ?>' rel='stylesheet' type='text/css'>
        <?php endforeach; ?>


    </head> 
    <body id="page-<?= $this->request->action; ?>">  
        <div id="flash-messenger"><?= $this->session->flash_message() ?></div>
        <div id="loading"><?= $this->icon('spinner', 'spin') ?></div>

        <?php $this->load_layout(); ?>

        <?php $this->google_analytics() ?>

    </body>
</html>