
    <?php if ($action == 'list') : ?>

        <section>

            <a href="<?= $url ?>?action=form" id="add-client" class="button pull-right inverse"><?= $this->icon('user-plus') ?>  Nouveau client</a> 

            <h2>Liste des clients</h2>

            <div class="col-lg-12 table-responsive">
                <?= $table->draw() ?>
            </div>

        </section>


    <?php elseif ($action == 'view') : ?>

        <section>

            <a href="<?= $url ?>?action=list" class="return-arrow" style="position:absolute; right:0px; top:0px;">
                <?= $this->icon('arrow-left') ?>
            </a>

            <h2><?= $client->name ?> ( ID <?= $client->id ?> )</h2>

            <table border="0" cellpadding="10" >
            	<tr>
            		<td width="150"><b>Client</b></td>
            		<td><?= $client->name ?></td>
            	</tr>
                <tr>
                    <td width="150"><b>Contact</b></td>
                    <td><?= $client->contact_name ?></td>
                </tr>
            	<tr>
            		<td><b>Email</b></td>
            		<td><?= $client->email ?></td>
            	</tr>
                <tr>
                    <td width="150"><b>Adresse</b></td>
                    <td><?= $client->address ?></td>
                </tr>
                <tr>
                    <td><b>Téléphone mobile</b></td>
                    <td><?= $client->mobile ?></td>
                </tr>
            	<tr>
            		<td><b>Téléphone</b></td>
            		<td><?= $client->phone ?></td>
            	</tr>
                <tr>
                    <td><b>Accès admin</b></td>
                    <td><?= $client->access_admin == 0 ? 'Non' : 'Oui' ?></td>
                </tr>
            	<tr>
            		<td><b>Date de création</b></td>
            		<td><?= \Core\Tools::convert_date($client->date_create) ?></td>
            	</tr>
            </table>

        </section>


    <?php elseif ($action == 'form') : ?>

        <section>

            <a href="<?= $url ?>?action=list" class="return-arrow" style="position:absolute; right:0px; top:0px;">
                <?= $this->icon('arrow-left') ?>
            </a>

            <h2><?= !$form->get('id')->value ? 'Ajouter' : 'Modifier' ?> un client</h2>

             <?= $form->draw(); ?>

            <div class="clear"></div>

        </section>


    <?php elseif ($action == 'create_admin') : ?>

        <section>
        	
            <a href="<?= $url ?>?action=list" class="return-arrow" style="position:absolute; right:0px; top:0px;">
                <?= $this->icon('arrow-left') ?>
            </a>

            <h2>Créer un compte admin</h2>

             <?= $form->draw(); ?>

            <div class="clear"></div>

        </section>

    <?php endif; ?>




