
<h2><?= $title ?></h2>

<form id="script-form" method="POST" action="" target="script_frame">
<select name="selected_script" style="padding:3px;">
	<option value="">-</option>
	<?php foreach($scripts as $script): ?>
		<option value="<?= $script ?>"><?= $script ?></option>
	<?php endforeach; ?>
</select>
<input type="text" name="vars" style="padding-left:5px;padding-right:5px; width:250px;" placeholder="Variables, séparés d'un &" />
<input type="submit" value="Executer" />
</form>
<br>
<iframe name="script_frame" style="background-color:#211e1e; border:0; max-width:900px; width:100%; height:500px;">
</iframe>

<script>
$('#script-form').on('submit', function(event){
	var file = $(this).find('select option:selected').val();
	return confirm('Lancer le script '+file+' ?');
});
</script>

