
        <header>

            <div id="logo">
                <a href="<?= $this->url('front-page-home') ?>">
                    <img src="<?= $this->img('logo_inner.png'); ?>" border="0" />
                </a>
            </div>

            <?= $this->menu('header') ?>
            
        </header>

        <section id="main-container">

            <div class="container-fluid"> 
            
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    
                    
                    
                    </div>
                </div>

                <div class="clear"></div>

                <footer>

                </footer>
            
            </div>

        </section>